runtime: python27
api_version: 1
threadsafe: true

# order matters; /.* should be at the bottom since it matches everything
handlers:
- url: /static
  static_dir: static

- url : /crons/subscriptionemails
  script : main.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
